stages:
  - compile
  - build
  - deploy

variables:
  CI_REGISTRY_USER: topanbegin
  CI_REGISTRY_PASSWORD: fnW6xKQbxB5GzzGfFzXz
  CI_REGISTRY: 10.14.204.20:5005

  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

Compile NPM:
  stage: compile
  image: node:12.22.1-alpine
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
  before_script:
    - node --version
  script:
    - >
      if [ "$CI_COMMIT_REF_NAME" == "development" ]; then
        cp .env.development .env &&
        npm install &&
        npm run build
      else
        echo "No Process"
      fi
  artifacts:
    name: "dist-$CI_COMMIT_REF_NAME"
    paths:
      - dist/spa/
    expire_in: 1 hour
  tags:
    - docker

Build Container:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --no-cache -t $DOCKER_IMAGE --build-arg DIST=dist/spa -f deploy/Dockerfile .
    - docker push $DOCKER_IMAGE
  only:
    - development

Deploy Development:
  stage: deploy
  script:
    - kubectl rollout restart deploy/airsale-sambal-ganja -n development
  environment:
    name: URL Development
    url: https://web-blue.air.id/airsale-sambal-ganja
  only:
    - development
